# Generated by Django 4.1.7 on 2023-02-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='position',
            field=models.CharField(default='', max_length=150),
        ),
    ]
