# Generated by Django 4.1.7 on 2023-02-20 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('track', '0003_alter_application_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_amount',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='application',
            name='localization',
            field=models.CharField(default='Wrocław', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='position',
            field=models.CharField(default='Python Developer', max_length=150),
        ),
        migrations.AlterField(
            model_name='application',
            name='result',
            field=models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'rejected'), ('under consideration', 'under consideration')], default='under consideration', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(default='aga', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
